spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

paths:
  external-api:
    majorCurrenciesUrl: 'https://www.freeforexapi.com/api/live?pairs='

currency:
  symbols:
    - EURUSD
    - EURGBP
    - GBPUSD
    - USDJPY
    - AUDUSD
    - USDCHF
    - NZDUSD
    - USDCAD
